#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [[ "${1-}" == "--reset" ]]; then
    rm -rf target doublebundle/dist
fi

doublebundle/scripts/rebuild-double-bundle

exec clj -m figwheel.main -b common:dev -r
