#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [[ "${1-}" == "--reset" ]]; then
    rm -rf target-prod doublebundle/dist
fi

doublebundle/scripts/rebuild-double-bundle

rm -rf dist

clojure -A:prod

cp -r resources/public/* dist/

echo All done, see the dist/ directory
