#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [[ "${1-}" == "--reset" ]]; then
    rm -rf target doublebundle/dist
fi

doublebundle/scripts/rebuild-double-bundle

mkdir -p target

clj -m figwheel.main -co dev.cljs.edn -fwo '{:launch-js "scripts/headless-chrome"}' -m cljs-spa.test-runner
